import { IUser } from './store/user/UserReducer';

export const USERS: Array<IUser & { password: string }> = [
  {
    id: 1,
    username: 'user1',
    password: 'user1pass',
    employeeId: 1,
    employeeGroup: [],
  },
  {
    id: 2,
    username: 'user2',
    password: 'user2pass',
    employeeId: 2,
    employeeGroup: [
      {
        employeeId: 1,
        order: 2,
      },
      {
        employeeId: 10,
        order: 1,
      },
      {
        employeeId: 3,
        order: 4,
      },
      {
        employeeId: 4,
        order: 3,
      },
      {
        employeeId: 5,
        order: 5,
      },
    ],
  },
  {
    id: 3,
    username: 'user3',
    password: 'user3pass',
    employeeId: null,
    employeeGroup: [],
  },
];

export const EMPLOYEES = [
  {
    id: 1,
    firstName: 'Marigold',
    lastName: 'Sealey',
    email: 'msealey0@techcrunch.com',
    gender: 'Female',
    department: 'Marketing',
    jobTitle: 'Analog Circuit Design manager',
    country: 'China',
    city: 'Damaying',
  },
  {
    id: 2,
    firstName: 'Lanita',
    lastName: 'Yves',
    email: 'lyves1@hugedomains.com',
    gender: 'Female',
    department: 'Support',
    jobTitle: 'Web Designer II',
    country: 'Japan',
    city: 'Hirakata',
  },
  {
    id: 3,
    firstName: 'Donny',
    lastName: 'Mannakee',
    email: 'dmannakee2@psu.edu',
    gender: 'Female',
    department: 'Human Resources',
    jobTitle: 'Health Coach II',
    country: 'Armenia',
    city: 'Sevan',
  },
  {
    id: 4,
    firstName: 'Dodi',
    lastName: 'Flecknell',
    email: 'dflecknell3@vkontakte.ru',
    gender: 'Female',
    department: 'Product Management',
    jobTitle: 'Senior Editor',
    country: 'Norway',
    city: 'Drammen',
  },
  {
    id: 5,
    firstName: 'Marci',
    lastName: 'Clink',
    email: 'mclink4@netscape.com',
    gender: 'Female',
    department: 'Human Resources',
    jobTitle: 'Nuclear Power Engineer',
    country: 'Russia',
    city: 'Nytva',
  },
  {
    id: 6,
    firstName: 'Harv',
    lastName: 'Cowitz',
    email: 'hcowitz5@mozilla.org',
    gender: 'Male',
    department: 'Services',
    jobTitle: 'Account Coordinator',
    country: 'Uganda',
    city: 'Entebbe',
  },
  {
    id: 7,
    firstName: 'Fonz',
    lastName: 'Timmermann',
    email: 'ftimmermann6@nba.com',
    gender: 'Male',
    department: 'Legal',
    jobTitle: 'Geological Engineer',
    country: 'Russia',
    city: 'Cherkasskoye',
  },
  {
    id: 8,
    firstName: 'Hastie',
    lastName: 'Loughton',
    email: 'hloughton7@drupal.org',
    gender: 'Male',
    department: 'Product Management',
    jobTitle: 'Recruiting Manager',
    country: 'China',
    city: 'Jinzhuang',
  },
  {
    id: 9,
    firstName: 'Deck',
    lastName: 'Gooday',
    email: 'dgooday8@xing.com',
    gender: 'Male',
    department: 'Legal',
    jobTitle: 'Speech Pathologist',
    country: 'Egypt',
    city: 'Isnā',
  },
  {
    id: 10,
    firstName: 'Venita',
    lastName: 'Kissock',
    email: 'vkissock9@discovery.com',
    gender: 'Female',
    department: 'Services',
    jobTitle: 'Account Representative IV',
    country: 'Portugal',
    city: 'Foros de Salvaterra',
  },
  {
    id: 11,
    firstName: 'Leonid',
    lastName: 'Farryan',
    email: 'lfarryana@meetup.com',
    gender: 'Male',
    department: 'Accounting',
    jobTitle: 'Research Nurse',
    country: 'Russia',
    city: 'Lyalichi',
  },
  {
    id: 12,
    firstName: 'Mirabella',
    lastName: 'Lambart',
    email: 'mlambartb@artisteer.com',
    gender: 'Female',
    department: 'Support',
    jobTitle: 'Systems Administrator III',
    country: 'Honduras',
    city: 'Marale',
  },
  {
    id: 13,
    firstName: 'Farlee',
    lastName: 'Oldknowe',
    email: 'foldknowec@imageshack.us',
    gender: 'Male',
    department: 'Sales',
    jobTitle: 'Help Desk Technician',
    country: 'Egypt',
    city: 'Dishnā',
  },
  {
    id: 14,
    firstName: 'Blayne',
    lastName: 'Browse',
    email: 'bbrowsed@infoseek.co.jp',
    gender: 'Male',
    department: 'Legal',
    jobTitle: 'Senior Developer',
    country: 'Nigeria',
    city: 'Gusau',
  },
  {
    id: 15,
    firstName: 'Jaymee',
    lastName: 'Dimblebee',
    email: 'jdimblebeee@arstechnica.com',
    gender: 'Female',
    department: 'Legal',
    jobTitle: 'Engineer IV',
    country: 'Portugal',
    city: 'Ortiga',
  },
  {
    id: 16,
    firstName: 'Greta',
    lastName: 'Plackstone',
    email: 'gplackstonef@economist.com',
    gender: 'Female',
    department: 'Accounting',
    jobTitle: 'Computer Systems Analyst IV',
    country: 'China',
    city: 'Kanshi',
  },
  {
    id: 17,
    firstName: 'Thomasin',
    lastName: 'de Banke',
    email: 'tdebankeg@engadget.com',
    gender: 'Female',
    department: 'Product Management',
    jobTitle: 'Safety Technician I',
    country: 'Finland',
    city: 'Varkaus',
  },
  {
    id: 18,
    firstName: 'Julian',
    lastName: 'Jertz',
    email: 'jjertzh@google.it',
    gender: 'Male',
    department: 'Support',
    jobTitle: 'Design Engineer',
    country: 'Indonesia',
    city: 'Nobo',
  },
  {
    id: 19,
    firstName: 'Donelle',
    lastName: 'Gregol',
    email: 'dgregoli@barnesandnoble.com',
    gender: 'Female',
    department: 'Human Resources',
    jobTitle: 'Programmer I',
    country: 'Portugal',
    city: 'Pedrogão',
  },
  {
    id: 20,
    firstName: 'Elie',
    lastName: 'Farish',
    email: 'efarishj@chron.com',
    gender: 'Female',
    department: 'Human Resources',
    jobTitle: 'Compensation Analyst',
    country: 'China',
    city: 'Changfeng',
  },
];
